### ISSUE TITLE
Realesed JAR doesn't work with Java 11

### ISSUE THREAD

**Issue by Marqin** [jepsen-io/maelstrom#3]
I'm getting this error when trying to run JAR from releases:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
[...] here long clj stacktrace [...]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2181)
        at org.httpkit.server$loading__5569__auto____6381.invoke(server.clj:1)
        at org.httpkit.server__init.load(Unknown Source)
        at org.httpkit.server__init.<clinit>(Unknown Source)
        ... 98 more
```

[According to SO](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) the problem is removal of this library in new Java versions: `In Java 11 they are completely removed from the JDK.`

**Comment by Marqin** [comment]
Trying to build from repo HEAD with `lein uberjar` also gives this error.

**Comment by aphyr** [comment]
The latest release, 0.2.0, works with JDK8 through 14 at least. :)
