### ISSUE TITLE
Trying to set this up, but getting error=13, Permission denied

### ISSUE THREAD

**Issue by chiroptical** [jepsen-io/maelstrom#37]
I download the `echo.rb` file and I am running

```
maelstrom test -w echo --bin echo.rb --time-limit 5
```

```
INFO [2023-02-23 18:21:56,703] jepsen node n1 - maelstrom.db Setting up n1
INFO [2023-02-23 18:21:56,703] jepsen node n1 - maelstrom.process launching echo.rb []
INFO [2023-02-23 18:21:57,715] jepsen node n1 - maelstrom.net Shutting down Maelstrom network
WARN [2023-02-23 18:21:57,716] jepsen test runner - jepsen.core Test crashed!
java.io.IOException: Cannot run program "/home/barry/programming/haskell/maelstromHs/echo.rb" (in directory "/tmp"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
```

I also tried `sudo ...`. I also tried executing it directly from `/tmp` (same error).

I don't get permission denied from, e.g.,

```
cd /tmp
touch example.file
```

Not really sure what to do here.

**Comment by chiroptical** [comment]
Ignore this! It expects `echo.rb` to be executable.
