### ISSUE TITLE
jepsen.checker AssertionError when running lin-kv with partition nemesis

### ISSUE THREAD

**Issue by codekitchen** [jepsen-io/maelstrom#92]
Hi! I often, but don't always, get this AssertionError when running the lin-kv workload with the `--nemesis partition` option. I never get the error without that nemesis option.

It seems to always trigger a linearizable failure as well, but the reported CAS register key is nil:

```
                      10 {:linearizable {:valid? false,
                                         :configs ({:model #knossos.model.CASRegister{:value nil},
```

I've added stderr logging to my binary and I don't see any `"key":null` being passed in the json messages to my code, they're all integer keys. It's hard for me to be certain whether any problems in my implementation could be contributing to this error.

I originally saw the error using the 0.2.3 release binary, but I've reproduced it on the latest main branch as well using this command:

```
lein run test -w lin-kv --bin ../liferaft/maelstrom_client --node-count 3 --concurrency 4n --rate 30 --time-limit 60 --test-count 10 --nemesis partition --log-stderr
```

Error stack trace:

```
INFO [2024-11-26 16:34:02,623] jepsen node n0 - maelstrom.net Shutting down Maelstrom network
INFO [2024-11-26 16:34:02,627] jepsen test runner - jepsen.core Analyzing...
WARN [2024-11-26 16:34:02,764] clojure-agent-send-off-pool-130 - jepsen.checker Error rendering linearizability analysis
java.lang.AssertionError: Assert failed: Expected index but got nil for op #knossos.op.Op{:process nil, :type nil, :f nil, :value nil, :index nil}
i
        at knossos.linear.report$time_coords$fn__11689.invoke(report.clj:184)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$into.invokeStatic(core.clj:6958)
        at clojure.core$into.invoke(core.clj:6950)
        at knossos.linear.report$time_coords.invokeStatic(report.clj:194)
        at knossos.linear.report$time_coords.invoke(report.clj:177)
        at knossos.linear.report$learnings.invokeStatic(report.clj:442)
        at knossos.linear.report$learnings.invoke(report.clj:422)
        at knossos.linear.report$render_analysis_BANG_.invokeStatic(report.clj:654)
        at knossos.linear.report$render_analysis_BANG_.invoke(report.clj:649)
        at jepsen.checker$linearizable$reify__11926$fn__11928.invoke(checker.clj:224)
        at jepsen.checker$linearizable$reify__11926.check(checker.clj:222)
        at jepsen.checker$check_safe.invokeStatic(checker.clj:86)
        at jepsen.checker$check_safe.invoke(checker.clj:79)
        at jepsen.checker$compose$reify__11881$fn__11883.invoke(checker.clj:102)
        at clojure.core$pmap$fn__8552$fn__8553.invoke(core.clj:7089)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by aphyr** [comment]
The initial state of a register is `nil`--it might be that the only legal state of the register at the time of the failure was one resulting from no writes or cas operations... That help at all?

**Comment by aphyr** [comment]
Ohhhh hang on, I didn't understand--`#knossos.op.Op{:process nil, :type nil, :f nil, :value nil, :index nil}`, thaaaaat suggests to me that somehow we're constructing a blank map or `nil` operation from `client/invoke!`. Do you have the `history.edn` file, perhaps? Even better would be a zip of `store/latest` (or whatever the test run was).

**Comment by codekitchen** [comment]
I will try to find some time to dig into this, I'd really like to get my code passing this Maelstrom case cleanly. Thanks for the pointers on where to look, that helps a ton. I'm not familiar with Clojure but with this general idea of where to look, hopefully I can track it down.

**Comment by codekitchen** [comment]
OK, I took a dive into the Maelstrom/Jepsen/Knossos code with the help of a colleague, and I think we have a pretty good understanding of this bug now. It's actually the same bug as [this issue](https://github.com/jepsen-io/knossos/issues/36), but it's manifesting "in the wild" through a Maelstrom run rather than the hand-written history file in that other issue. The problem is when the very first successful op causes the analysis to fail. This causes the `:final-paths` returned from the analysis to include a null op, which later causes the report rendering code to fail that assert. I *think* the null op comes from `:last-op` being null on the config in the call to `linear/final-paths`, but I'm less certain on that point.

I was able to whittle down my run's `independent/2/history.edn` file into this minimal repro that still causes the assertion failure:

```
{:index 349, :time 12638526125, :type :invoke, :process 1, :f :read, :value nil}
{:index 361, :time 12992297125, :type :invoke, :process 101, :f :write, :value 3}
{:index 384, :time 13995187167, :type :fail, :process 101, :f :write, :value 3, :error [:temporarily-unavailable nil]}
{:index 402, :time 14796437042, :type :ok, :process 1, :f :read, :value 3}
```

There is a bug in my implementation and this invalid result from the analysis looks legit -- responding with `:temporarily-unavailable` but then actually persisting the write. I see where the bug is, not in my core Raft algorithm but in my Maelstrom client wrapper.

But my question is, how should this assertion failure be fixed? Two options I see are:

1. Modify the report rendering code to deal with a nil op
2. Modify the analysis code to no longer return a nil op in `:final-paths`

The second option seems like probably the more correct one? Or at least, with my current understanding of Knossos, it doesn't seem correct to have these nil ops as part of the analysis path. But I don't know exactly how to make that fix yet, or what the consequences elsewhere in Jepsen could be. What do you think?

By the way, I see some other odd things in `results.edn` when hitting this problem, but I don't know how relevant they are to this bug. The final-paths for the failing linearizability test have some missing text like "can't CAS  from 0 to 4" (missing the register number) and the same test seems to be operating on two registers, 0 and 4. "can't read 1 from register 0" followed by "can't CAS 4 from 3 to 1".

**Comment by aphyr** [comment]
Ahhhh yes, I remember this now! Good find!

It's been... probably six years since I've been in this part of Knossos' code, so my intuition is also rusty. I think you're on the right track with option 2: `final-paths` should probably not be returning nil operations at all. I think I'd start by taking that minimal example history you've got and putting that into a test case which asserts that `(:final-paths results)` coming out of `wgl/check` and `linear/check` don't have nil elements. I suspect the bug will be in those functions, or maybe in `analysis/final-paths-for-config`.

**Comment by codekitchen** [comment]
Fixed by https://github.com/jepsen-io/knossos/pull/37
